spring:
  application:
    name: eureka-server
  profiles:
    active:
      - dev
  config:
    import: optional:configserver:http://localhost:9010
    #import: optional:configserver:http://config-server:9010
  cloud:
    config:
      profile: dev
      fail-fast: true